export const data = [
    {
        num: 1,
        name: '1/10 GRANITE VOLTAGE 2WD Brushed Mega Monster Truck RTR',
        id: 'ARA102727',
        manufacturer: 'ARRMA RC',
        inStock: 4,
        price: 129.99,
        colors: ['blue', 'red', 'black'],
        type: 'Ground',
        level: 'beginner',
        img: './assets/jpg/ARA102727_A0_8K0Y8R2G.jpg',
    },
    {
        num: 2,
        name: '1/10 GRANITE 4WD V3 3S BLX Brushless Monster Truck RTR',
        id: 'ARA4302V3',
        manufacturer: 'ARRMA RC',
        inStock: 3,
        price: 339.99,
        colors: ['green', 'red'],
        type: 'Ground',
        level: 'beginner',
        img: './assets/jpg/ARA4302V3_A0_MEU77BNV.jpg',
    },
    {
        num: 3,
        name: '1/8 KRATON 6S V5 4WD BLX Speed Monster Truck with Spektrum Firma RTR',
        id: 'ARA8608V5',
        manufacturer: 'ARRMA RC',
        inStock: 2,
        price: 549.99,
        colors: ['blue', 'red'],
        type: 'Ground',
        level: 'experienced',
        img: './assets/jpg/ARA8608V5_A00_J6P80WZ6.jpg',
    },
    {
        num: 4,
        name: '1/5 KRATON 4WD 8S BLX Brushless Speed Monster Truck RTR',
        id: 'ARA110002',
        manufacturer: 'ARRMA RC',
        inStock: 1,
        price: 969.99,
        colors: ['green'],
        type: 'Ground',
        level: 'professional',
        img: './assets/jpg/ARA110002_A0_D9NLOKNG.jpg',
    },
    {
        num: 5,
        name: '1/10 KRATON 4X4 4S V2 BLX Speed Monster Truck RTR',
        id: 'ARA4408V2',
        manufacturer: 'ARRMA RC',
        inStock: 6,
        price: 469.99,
        colors: ['green', 'blue'],
        type: 'Ground',
        level: 'experienced',
        img: './assets/jpg/ARA4408V2_A31_1J2TZNUE.jpg',
    },
    {
        num: 6,
        name: '1/10 OUTCAST 4X4 4S V2 BLX Stunt Truck RTR',
        id: 'ARA4410V2',
        manufacturer: 'ARRMA RC',
        inStock: 4,
        price: 469.99,
        colors: ['blue'],
        type: 'Ground',
        level: 'experienced',
        img: './assets/jpg/ARA4410V2_A1_6ZKRDYXU.jpg',
    },
    {
        num: 7,
        name: '1/8 VENDETTA 4WD 3S BLX Brushless All-Road Speed Bash Racer',
        id: 'ARA4319V3',
        manufacturer: 'ARRMA RC',
        inStock: 4,
        price: 369.99,
        colors: ['blue', 'green'],
        type: 'Ground',
        level: 'experienced',
        img: './assets/jpg/ARA4319V3_A39_AV7FKOSS.jpg',
    },
    {
        num: 8,
        name: '1/7 FELONY 6S BLX Street Bash All-Road Muscle Car RTR',
        id: 'ARA7617V2',
        manufacturer: 'ARRMA RC',
        inStock: 1,
        price: 649.99,
        colors: ['black'],
        type: 'Ground',
        level: 'professional',
        img: './assets/jpg/ARA7617V2_A00_HXFUGCYH.jpg',
    },
    {
        num: 9,
        name: '1/8 INFRACTION 4WD MEGA Resto-Mod Truck RTR',
        id: 'ARA4215V3',
        manufacturer: 'ARRMA RC',
        inStock: 8,
        price: 299.99,
        colors: ['blue', 'red'],
        type: 'Ground',
        level: 'beginner',
        img: './assets/jpg/ARA4215V3_A45_L7V85QKR.jpg',
    },
    {
        num: 10,
        name: '1/7 INFRACTION 6S BLX V2 All-Road Truck RTR',
        id: 'ARA7615V2',
        manufacturer: 'ARRMA RC',
        inStock: 3,
        price: 649.99,
        colors: ['blue'],
        type: 'Ground',
        level: 'experienced',
        img: './assets/jpg/ARA7615V2_A00_VVLGIV0P.jpg',
    },
    {
        num: 11,
        name: '1/6 SCX6 Jeep JLU Wrangler 4WD Rock Crawler RTR',
        id: 'AXI05000',
        manufacturer: 'Axial RC',
        inStock: 2,
        price: 1099.99,
        colors: ['green'],
        type: 'Ground',
        level: 'experienced',
        img: './assets/jpg/AXI05000_A7_8QW1G766.jpg',
    },
    {
        num: 12,
        name: '1/10 SCX10 III Base Camp 4WD Rock Crawler Brushed RTR',
        id: 'AXI03027',
        manufacturer: 'Axial RC',
        inStock: 7,
        price: 389.99,
        colors: ['green', 'blue'],
        type: 'Ground',
        level: 'beginner',
        img: './assets/jpg/AXI03027_A2_68L2IVW8.jpg',
    },
    {
        num: 13,
        name: '1/10 SCX10III Jeep JT Gladiator with Portals RTR',
        id: 'AXI03006B',
        manufacturer: 'Axial RC',
        inStock: 2,
        price: 529.99,
        colors: ['black'],
        type: 'Ground',
        level: 'beginner',
        img: './assets/jpg/AXI03006B_A0_E28KMLTG.jpg',
    },
    {
        num: 14,
        name: '1/10 Capra 1.9 4WS Unlimited Trail Buggy RTR',
        id: 'AXI03022',
        manufacturer: 'Axial RC',
        inStock: 5,
        price: 549.99,
        colors: ['black', 'red'],
        type: 'Ground',
        level: 'beginner',
        img: './assets/jpg/AXI03022_A01_WJPHKM20.jpg',
    },
    {
        num: 15,
        name: '1/10 RBX10 Ryft 4WD Rock Bouncer Kit, Gray',
        id: 'AXI03009',
        manufacturer: 'Axial RC',
        inStock: 3,
        price: 329.99,
        colors: ['blue'],
        type: 'Ground',
        level: 'beginner',
        img: './assets/jpg/AXI03009_A10_L963KB47.jpg',
    },
    {
        num: 16,
        name: '1/18 Yeti Jr. Can-Am Maverick 4WD Brushed RTR',
        id: 'AXI90069',
        manufacturer: 'Axial RC',
        inStock: 2,
        price: 174.99,
        colors: ['black'],
        type: 'Ground',
        level: 'beginner',
        img: './assets/jpg/AXI90069_A0_5GHRCI1S.jpg',
    },
    {
        num: 17,
        name: 'Nano S3 RTF with AS3X and SAFE',
        id: 'BLH01300',
        manufacturer: 'Blade',
        inStock: 11,
        price: 159.99,
        colors: ['blue'],
        type: 'Air',
        level: 'beginner',
        img: './assets/jpg/BLH01300_A00_G5TBTR1R.jpg',
    },
    {
        num: 18,
        name: 'Fusion 480 Smart Super Combo Kit',
        id: 'BLH4925SC2',
        manufacturer: 'Blade',
        inStock: 4,
        price: 999.99,
        colors: ['green'],
        type: 'Air',
        level: 'experienced',
        img: './assets/jpg/BLH4925SC2_A0_0JM6MAA6.jpg',
    },
    {
        num: 19,
        name: 'InFusion 180 BNF Basic',
        id: 'BLH7050',
        manufacturer: 'Blade',
        inStock: 8,
        price: 299.99,
        colors: ['green', 'red'],
        type: 'Air',
        level: 'beginner',
        img: './assets/jpg/BLH7050_A0_EJQ7MGOV.jpg',
    },
    {
        num: 20,
        name: 'Fusion 180 Smart BNF Basic',
        id: 'BLH05850',
        manufacturer: 'Blade',
        inStock: 8,
        price: 279.99,
        colors: ['green', 'black'],
        type: 'Air',
        level: 'beginner',
        img: './assets/jpg/BLH05850_A0_SZZOO2NL.jpg',
    },
    {
        num: 21,
        name: '150 S Smart BNF Basic with AS3X and SAFE',
        id: 'BLH54550',
        manufacturer: 'Blade',
        inStock: 3,
        price: 229.99,
        colors: ['green', 'black'],
        type: 'Air',
        level: 'beginner',
        img: './assets/jpg/BLH05850_A0_SZZOO2NL.jpg',
    },
    {
        num: 22,
        name: 'Timber X 1.2m BNF Basic with AS3X and SAFE Select',
        id: 'EFL38500',
        manufacturer: 'E-flite',
        inStock: 14,
        price: 229.99,
        colors: ['green'],
        type: 'Air',
        level: 'beginner',
        img: './assets/jpg/EFL38500_A00_82G9GEE2.jpg',
    },
    {
        num: 23,
        name: 'DRACO 2.0m Smart PNP',
        id: 'EFL12575',
        manufacturer: 'E-flite',
        inStock: 6,
        price: 599.99,
        colors: ['red'],
        type: 'Air',
        level: 'experienced',
        img: './assets/jpg/EFL12575_A00_SFF5Y9J2.jpg',
    },
    {
        num: 24,
        name: 'Night Radian 2.0m PNP',
        id: 'EFL36750',
        manufacturer: 'E-flite',
        inStock: 5,
        price: 219.99,
        colors: ['red'],
        type: 'Air',
        level: 'beginner',
        img: './assets/jpg/EFL36750_A00_JCGR9MJH.jpg',
    },
    {
        num: 25,
        name: 'F-15 Eagle 64mm EDF Jet BNF Basic with AS3X and SAFE Select',
        id: 'EFL97500',
        manufacturer: 'E-flite',
        inStock: 3,
        price: 229.99,
        colors: ['blue'],
        type: 'Air',
        level: 'beginner',
        img: './assets/jpg/EFL97500_A00_AZXQEKRY.jpg',
    },
    {
        num: 26,
        name: 'Habu SS (Super Sport) 70mm EDF Jet PNP',
        id: 'EFL0975',
        manufacturer: 'E-flite',
        inStock: 1,
        price: 279.99,
        colors: ['yellow'],
        type: 'Air',
        level: 'beginner',
        img: './assets/jpg/EFL0975_A97_PKJ9S41C.jpg',
    },
    {
        num: 27,
        name: 'V1200 1.2m BNF Basic with Smart, AS3X and SAFE Select',
        id: 'EFL12350',
        manufacturer: 'E-flite',
        inStock: 6,
        price: 399.99,
        colors: ['blue'],
        type: 'Air',
        level: 'experienced',
        img: './assets/jpg/EFL12350_A00_2T2569MU.jpg',
    },
    {
        num: 28,
        name: 'Carbon-Z Cessna 150T 2.1m PNP',
        id: 'EFL12775',
        manufacturer: 'E-flite',
        inStock: 2,
        price: 469.99,
        colors: ['blue'],
        type: 'Air',
        level: 'professional',
        img: './assets/jpg/EFL12775_A00_UNYYFSW4.jpg',
    },
    {
        num: 29,
        name: 'Mini AeroScout RTF',
        id: 'HBZ5700',
        manufacturer: 'HobbyZone',
        inStock: 6,
        price: 119.99,
        colors: ['red'],
        type: 'Air',
        level: 'beginner',
        img: './assets/jpg/HBZ5700_A00_00OUH6FL.jpg',
    },
    {
        num: 30,
        name: 'Sport Cub S 2 BNF Basic with SAFE',
        id: 'HBZ44500',
        manufacturer: 'HobbyZone',
        inStock: 4,
        price: 119.99,
        colors: ['blue'],
        type: 'Air',
        level: 'beginner',
        img: './assets/jpg/HBZ44500_A0_JQ6HNKKL.jpg',
    },
    {
        num: 31,
        name: 'Carbon Cub S 2 1.3m Chandra Patey Limited Edition RTF',
        id: 'HBZ32000LE',
        manufacturer: 'HobbyZone',
        inStock: 3,
        price: 449.99,
        colors: ['yellow', 'blue'],
        type: 'Air',
        level: 'experienced',
        img: './assets/jpg/HBZ32000LE_A20_LLX6GX2K.jpg',
    },
    {
        num: 32,
        name: 'Apprentice S 2 1.2m RTF with SAFE',
        id: 'HBZ31000',
        manufacturer: 'HobbyZone',
        inStock: 13,
        price: 299.99,
        colors: ['red', 'blue'],
        type: 'Air',
        level: 'experienced',
        img: './assets/jpg/HBZ31000_A08_1D2F1L9R.jpg',
    },
    {
        num: 33,
        name: 'AeroScout S 2 1.1m RTF with SAFE',
        id: 'HBZ38000',
        manufacturer: 'HobbyZone',
        inStock: 4,
        price: 199.99,
        colors: ['red', 'black', 'green'],
        type: 'Air',
        level: 'experienced',
        img: './assets/jpg/HBZ38000_A00_TQNMKRZV.jpg',
    },
    {
        num: 34,
        name: 'Duet RTF, 523mm',
        id: 'HBZ5300',
        manufacturer: 'HobbyZone',
        inStock: 21,
        price: 79.99,
        colors: ['yellow', 'black', 'green', 'blue'],
        type: 'Air',
        level: 'beginner',
        img: './assets/jpg/HBZ5300_A0_GIYEROU1.jpg',
    },
    {
        num: 35,
        name: 'Apprentice S 2 1.2m BNF Basic with SAFE',
        id: 'HBZ31500',
        manufacturer: 'HobbyZone',
        inStock: 11,
        price: 249.99,
        colors: ['green', 'blue'],
        type: 'Air',
        level: 'beginner',
        img: './assets/jpg/HBZ31500_A00_KK2LQK7N.jpg',
    },
];
