export const filters = {
    // isActive: false,
    manufacturer: {
        'price-lowest': false,
        'price-highest': false,
        'Name(A-Z)': false,
        'Name(Z-A)': false,
        'ARRMA RC': false,
        'Axial RC': false,
        Blade: false,
        'E-flite': false,
        HobbyZone: false,
    },
    colors: {
        red: false,
        yellow: false,
        blue: false,
        green: false,
        black: false,
    },
    Air: false,
    Ground: false,
    Beginner: false,
    Professional: false,
    Experienced: false,
};
